# Generated by Django 4.2.1 on 2023-05-28 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan", models.CharField(max_length=64, verbose_name="Stamm")),
                (
                    "district",
                    models.CharField(max_length=128, verbose_name="Diözese / Bezirk"),
                ),
                ("first_name", models.CharField(max_length=64, verbose_name="Vorname")),
                ("last_name", models.CharField(max_length=64, verbose_name="Nachname")),
                ("participant_count", models.PositiveIntegerField()),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=16, verbose_name="Bestellungscode"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkshopPrintBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                ("position_id", models.PositiveIntegerField()),
                (
                    "weq",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Workshop Äquivalenz Punkte"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("A", "Neuer Workshop"),
                            ("E", "Workshop überarbeitet"),
                            ("V", "Workshop okay"),
                            ("R", "Workshop nicht okay"),
                            ("U", "Workshop unklar"),
                        ],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                ("annotated_id", models.PositiveIntegerField(null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.order"
                    ),
                ),
                (
                    "printed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.workshopprintbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_customer", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "old_status",
                    models.CharField(
                        choices=[
                            ("A", "Neuer Workshop"),
                            ("E", "Workshop überarbeitet"),
                            ("V", "Workshop okay"),
                            ("R", "Workshop nicht okay"),
                            ("U", "Workshop unklar"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Alter Status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("A", "Neuer Workshop"),
                            ("E", "Workshop überarbeitet"),
                            ("V", "Workshop okay"),
                            ("R", "Workshop nicht okay"),
                            ("U", "Workshop unklar"),
                        ],
                        max_length=1,
                        verbose_name="Neuer Status",
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=64, verbose_name="Betreff")),
                ("message", models.TextField(verbose_name="Nachricht")),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rcwsmgmt_logentries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.workshop"
                    ),
                ),
            ],
        ),
    ]
