# Generated by Django 4.2.1 on 2023-08-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
