# Generated by Django 4.2.1 on 2023-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_logentry_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="new_status",
            field=models.CharField(
                choices=[
                    ("A", "Neuer Workshop"),
                    ("E", "Workshop überarbeitet"),
                    ("V", "Workshop okay"),
                    ("X", "Workshop okay (Nicht drucken)"),
                    ("R", "Workshop nicht okay"),
                    ("U", "Workshop unklar"),
                    ("Z", "Workshop gelöscht"),
                ],
                max_length=1,
                verbose_name="Neuer Status",
            ),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="old_status",
            field=models.CharField(
                choices=[
                    ("A", "Neuer Workshop"),
                    ("E", "Workshop überarbeitet"),
                    ("V", "Workshop okay"),
                    ("X", "Workshop okay (Nicht drucken)"),
                    ("R", "Workshop nicht okay"),
                    ("U", "Workshop unklar"),
                    ("Z", "Workshop gelöscht"),
                ],
                max_length=1,
                null=True,
                verbose_name="Alter Status",
            ),
        ),
        migrations.AlterField(
            model_name="workshop",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Neuer Workshop"),
                    ("E", "Workshop überarbeitet"),
                    ("V", "Workshop okay"),
                    ("X", "Workshop okay (Nicht drucken)"),
                    ("R", "Workshop nicht okay"),
                    ("U", "Workshop unklar"),
                    ("Z", "Workshop gelöscht"),
                ],
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="WorkshopList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Name")),
                ("workshops", models.ManyToManyField(to="base.workshop")),
            ],
        ),
    ]
